### ISSUE TITLE
So many files in the root of the project gives a cluttered look!

### ISSUE THREAD

**Issue by aahnik** [gita/bhagavadgita-api-v2#1]
We can write isort configuration in `pyproject.toml`, and the python files can be moved into a package!

Shall I open a PR ? @samanyougarg

**Comment by samanyougarg** [comment]
@aahnik I created this repo to experiment with the code on [this repo](https://github.com/gita/bhagavadgita-api). Please have a look at that repo and submit a PR there.

**Comment by aahnik** [comment]
thanks! I see did not realize that. Once you merge this https://github.com/gita/bhagavadgita-api/pull/2 PR, I will submit mine.

The new project structure looks exciting!

**Comment by samanyougarg** [comment]
Awesome, thanks!
