### ISSUE TITLE
Major security vulnerability! username password exposed

### ISSUE THREAD

**Issue by aahnik** [gita/bhagavadgita-api-v2#2]
https://github.com/gita/bhagavadgita-api-v2/blob/582856132431677c8f7de8e6e8e6e4239467dd33/database.py#L7

Lets load the URL from environment variables.

using python-dotenv library would be good idea.

shall i open a pr ? @samanyougarg

**Comment by samanyougarg** [comment]
@aahnik I created this repo to experiment with the code on [this repo](https://github.com/gita/bhagavadgita-api). Please have a look at that repo and submit a PR there.
