### ISSUE TITLE
Is there any reason for hard coding python version ?

### ISSUE THREAD

**Issue by aahnik** [gita/bhagavadgita-api-v2#3]
https://github.com/gita/bhagavadgita-api-v2/blob/582856132431677c8f7de8e6e8e6e4239467dd33/pyproject.toml#L8-L9

from this line, and a glance at the source code, it looks that python 3.9 would also work smoothly.

then why are you restricting development to python3.8?

I believe nothing would break if this code is run using python3.9. It would be great to support anything > 3.8 but < 4.0

**Comment by samanyougarg** [comment]
@aahnik I created this repo to experiment with the code on [this repo](https://github.com/gita/bhagavadgita-api). Please have a look at that repo and submit a PR there.
